### ISSUE TITLE
Exception in thread "main" java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by softwarekamal** [benjwarner/stacked-off#11]
Please help I got that. after I run stacked-off.bat file.
I only install Java jdk-8u191-windows-x64.exe then run stacked-off.bat

I think I must change port. But I don't find the file .stackedoff/app.properties
Where is that file please?

```
14:53:16.575 [main] INFO org.tools4j.stacked.index.Instance - initializing conte
xt....
14:53:16.615 [main] INFO org.tools4j.stacked.index.Utils - Found userHomeDir at
[C:\Users\Dell]
14:53:16.615 [main] INFO org.tools4j.stacked.index.Utils - Could not find stacke
doff directory at [C:\Users\Dell\.stackedoff] so creating...
14:53:16.615 [main] INFO org.tools4j.stacked.index.Utils - Could not find stacke
doff application properties at [C:\Users\Dell\.stackedoff\app.properties] so cre
ating...
14:53:16.685 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory -
 Using SLF4J as the default logging framework
14:53:16.685 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.nett
y.eventLoopThreads: 16
14:53:16.725 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySe
tOptimization: false
14:53:16.725 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selecto
rAutoRebuildThreshold: 512
14:53:16.745 [main] DEBUG io.netty.util.internal.PlatformDependent - Platform: W
indows
14:53:16.755 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty
.noUnsafe: false
14:53:16.755 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java versi
on: 8
14:53:16.755 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.U
nsafe.theUnsafe: available
14:53:16.755 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.U
nsafe.copyMemory: available
14:53:16.755 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.B
uffer.address: available
14:53:16.755 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buf
fer constructor: available
14:53:16.755 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.B
its.unaligned: available, true
14:53:16.755 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.intern
al.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
14:53:16.765 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.D
irectByteBuffer.<init>(long, int): available
14:53:16.765 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Un
safe: available
14:53:16.765 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.
tmpdir: C:\Users\Dell\AppData\Local\Temp (java.io.tmpdir)
14:53:16.765 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.
bitMode: 64 (sun.arch.data.model)
14:53:16.765 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.
noPreferDirect: false
14:53:16.765 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.
maxDirectMemory: 3817865216 bytes
14:53:16.765 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.
uninitializedArrayAllocationThreshold: -1
14:53:16.765 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuf
fer.cleaner(): available
14:53:16.775 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools
-core.MpscChunkedArrayQueue: available
14:53:17.075 [main] INFO Application - No ktor.deployment.watch patterns specifi
ed, automatic reload is not active
14:53:17.275 [main] INFO Application - Responding at http://0.0.0.0:80
14:53:17.315 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.process
Id: 57200 (auto-detected)
14:53:17.315 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: fa
lse
14:53:17.315 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses
: false
14:53:17.395 [main] DEBUG io.netty.util.NetUtil - Loopback interface: lo (Softwa
re Loopback Interface 1, 127.0.0.1)
14:53:17.395 [main] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from s
ysctl and file \proc\sys\net\core\somaxconn. Default: 200
14:53:17.495 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machine
Id: 00:21:9b:ff:fe:69:07:a0 (auto-detected)
14:53:17.495 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.n
etty.threadLocalMap.stringBuilder.initialSize: 1024
14:53:17.495 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.n
etty.threadLocalMap.stringBuilder.maxSize: 4096
14:53:17.515 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDe
tection.level: simple
14:53:17.515 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDe
tection.targetRecords: 4
14:53:17.545 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.al
locator.numHeapArenas: 16
14:53:17.545 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.al
locator.numDirectArenas: 16
14:53:17.545 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.al
locator.pageSize: 8192
14:53:17.545 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.al
locator.maxOrder: 11
14:53:17.545 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.al
locator.chunkSize: 16777216
14:53:17.545 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.al
locator.tinyCacheSize: 512
14:53:17.545 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.al
locator.smallCacheSize: 256
14:53:17.545 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.al
locator.normalCacheSize: 64
14:53:17.545 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.al
locator.maxCachedBufferCapacity: 32768
14:53:17.545 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.al
locator.cacheTrimInterval: 8192
14:53:17.545 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.al
locator.useCacheForAllThreads: true
14:53:17.555 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.typ
e: pooled
14:53:17.555 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDi
rectBufferSize: 0
14:53:17.565 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLoca
lCharBufferSize: 16384
Exception in thread "main" java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSo
cketChannel.java:128)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.
java:558)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChann
elPipeline.java:1358)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractCha
nnelHandlerContext.java:501)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHa
ndlerContext.java:486)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.j
ava:1019)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366
)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEv
entExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(Single
ThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThread
EventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalR
unnable.java:30)
        at java.lang.Thread.run(Unknown Source)

```

**Comment by spaghettiScreen** [comment]
app.properties is located in C:\Users\username\.stackedoff
