### ISSUE TITLE
Import Issue on Raspberry Pi

### ISSUE THREAD

**Issue by GreatCanadianMoose** [benjwarner/stacked-off#12]
When trying to import on a raspberry pi:

`Parsing xml files in /NAS/stacked-off-1.0.1/stackexchange
Error parsing site askubuntu.com:
org.tools4j.stacked.index.UnknownExtractorException: Error occurred whilst parsing file [/NAS/stacked-off-1.0.1/stackexchange/askubuntu.com.7z] SevenZipJBinding couldn't be initialized automaticly using initialization from platform depended JAR and the default temporary directory. Please, make sure the correct 'sevenzipjbinding-.jar' file is on the class path or consider initializing SevenZipJBinding manualy using one of the offered initialization methods: 'net.sf.sevenzipjbinding.SevenZip.init*()'
	at org.tools4j.stacked.index.SeZipFileParser.parse(SeZipFileParser.kt:65)
	at org.tools4j.stacked.index.SeDirParser.parseSeSite(SeDirParser.kt:58)
	at org.tools4j.stacked.index.SeDirParser.parse(SeDirParser.kt:35)
	at org.tools4j.stacked.web.Server$Companion$mainServer$5$9$1.run(Server.kt:182)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: SevenZipJBinding couldn't be initialized automaticly using initialization from platform depended JAR and the default temporary directory. Please, make sure the correct 'sevenzipjbinding-.jar' file is on the class path or consider initializing SevenZipJBinding manualy using one of the offered initialization methods: 'net.sf.sevenzipjbinding.SevenZip.init*()'
	at net.sf.sevenzipjbinding.SevenZip.ensureLibraryIsInitialized(SevenZip.java:808)
	at net.sf.sevenzipjbinding.SevenZip.openInArchive(SevenZip.java:794)
	at org.tools4j.stacked.index.SeZipFileParser.parse(SeZipFileParser.kt:23)
	... 4 more
Caused by: net.sf.sevenzipjbinding.SevenZipNativeInitializationException: Error loading SevenZipJBinding native library into JVM: Can't find suited platform for os.arch=arm, os.name=Linux... Available list of platforms: Linux-amd64, Linux-i386, Mac-i386, Mac-x86_64, Windows-amd64, Windows-x86 [You may also try different SevenZipJBinding initialization methods 'net.sf.sevenzipjbinding.SevenZip.init*()' in order to solve this problem] 
	at net.sf.sevenzipjbinding.SevenZip.throwInitException(SevenZip.java:827)
	at net.sf.sevenzipjbinding.SevenZip.throwInitException(SevenZip.java:822)
	at net.sf.sevenzipjbinding.SevenZip.getPlatformBestMatch(SevenZip.java:897)
	at net.sf.sevenzipjbinding.SevenZip.determineAndSetUsedPlatform(SevenZip.java:465)
	at net.sf.sevenzipjbinding.SevenZip.initSevenZipFromPlatformJARIntern(SevenZip.java:450)
	at net.sf.sevenzipjbinding.SevenZip.initSevenZipFromPlatformJAR(SevenZip.java:339)
	at net.sf.sevenzipjbinding.SevenZip.ensureLibraryIsInitialized(SevenZip.java:805)
	... 6 more`

The second issue leads me to believe that there is an issue with the arm architecture, but I don't know what I'd need to compile.

**Comment by JacksonChen666** [comment]
> `Caused by: net.sf.sevenzipjbinding.SevenZipNativeInitializationException: Error loading SevenZipJBinding native library into JVM: Can't find suited platform for os.arch=arm, os.name=Linux... Available list of platforms: Linux-amd64, Linux-i386, Mac-i386, Mac-x86_64, Windows-amd64, Windows-x86 [You may also try different SevenZipJBinding initialization methods 'net.sf.sevenzipjbinding.SevenZip.init*()' in order to solve this problem]`

looks like you need [this](http://sevenzipjbind.sourceforge.net/) and build it in arm, but that's all i can figure out
