### ISSUE TITLE
Stability Issues

### ISSUE THREAD

**Issue by ADR995** [benjwarner/stacked-off#8]
I have installed and indexed successfully using the Jul 2020 dump - works great!
Now I am getting repetitive errors with Dec 2020 dump.

Several :
Write end dead child number [4138923] in file [Posts.xml] whilst parsing archive [C:\StackDump\stackoverflow.com-Posts.7z]

Note: the child number varies every time
Moving the entire OS, which is running on a VM to a different SSD seems to have solved that issue, only to terminate with the next error:

00:42:03.801 [Thread-8] DEBUG org.tools4j.stacked.index.SeZipFileParser - Parsing c:\StackDump\stackoverflow.com-Votes.7z
Exception in thread "Thread-8" java.lang.OutOfMemoryError: Java heap space
        at org.tools4j.stacked.index.UnscoredCollector.search(DocCollector.kt:51)
        at org.tools4j.stacked.index.DocIdIndex.searchByQueryForDocs(DocIdIndex.kt:121)
        at org.tools4j.stacked.index.DocIdIndex.searchByQuery(DocIdIndex.kt:117)
        at org.tools4j.stacked.index.DocIdIndex.searchByTerm(DocIdIndex.kt:80)
        at org.tools4j.stacked.index.DocIdIndex.searchByTerm(DocIdIndex.kt:84)
        at org.tools4j.stacked.index.QuestionIndexer$index$1.invokeSuspend(QuestionIndexer.kt:21)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:80)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at org.tools4j.stacked.index.QuestionIndexer.index(QuestionIndexer.kt:18)
        at org.tools4j.stacked.index.SeDirParserListener.onFinishParseSite(SeDirParserListener.kt:31)
        at org.tools4j.stacked.index.SeDirParser.parseSeSite(SeDirParser.kt:60)
        at org.tools4j.stacked.index.SeDirParser.parse(SeDirParser.kt:35)
        at org.tools4j.stacked.web.Server$Companion$mainServer$5$9$1.run(Server.kt:182)
        at java.lang.Thread.run(Unknown Source)

This occured in the same manner on  two VMs running with 4 and 8GB Memory

Is there any fix to this e.g. memory allocation in the startup script?
I have tried changing options:
set JAVA_OPTS="-Xms4096m -Xmx6144m"

with no success, propbably incorrect syntax

Thanks in advance for any help!

**Comment by Erdemhan** [comment]
Have the same error. Did you solve it ?
